#!/bin/env python3
"""
Usage:
[python] ./tester [-v] [top_level_directory=nj67-papers/testcases] [start_dir=nj67-papers/testcases]

top level dir is the current working directory (so all imports, etc)
start dir is where the tests come from
"""
import sys
from typing import TYPE_CHECKING
import unittest

if TYPE_CHECKING:
    # For the type checkers :)
    from _typeshed import OptExcInfo

class CustomTestResult(unittest.TestResult):
    "Extends unittest.TestResult by logging fails and errs in self.fails and self.errs, instead of formatted strings"
    def __init__(self):
        super().__init__()
        self.fails: list[tuple[unittest.TestCase, OptExcInfo]] = [] 
        self.errs: list[tuple[unittest.TestCase, OptExcInfo]] = []
    
    def addFailure(self, test, err):
        super().addFailure(test, err)
        self.fails.append((test, err))
    
    def addError(self, test, err):
        super().addError(test, err)
        self.errs.append((test, err))

if __name__ == "__main__": # Neccessary or no?
    VERBOSE = False
    while len(sys.argv) > 1 and sys.argv[1].startswith('-'):
        option = sys.argv.pop(1)
        if option in ('-v', '--verbose'):
            VERBOSE = True
    top_level_dir = "nj67-papers/testcases"
    start_dir = "nj67-papers/testcases"
    try:
        top_level_dir = sys.argv[1]
        start_dir = sys.argv[2]
    except IndexError:
        pass
    tests = unittest.TestLoader().discover(top_level_dir=top_level_dir, start_dir=start_dir)
    # tests.run() outputs the same type that was passed in (i.e. same object, just with functions called)
    res: CustomTestResult = tests.run(CustomTestResult()) #type: ignore
    if res.wasSuccessful():
        print("OK, no problem boss")
        sys.exit(0)
    else:
        for testcase, err in res.fails:
            print(f"Test failed in {testcase.__class__.__name__}: {err[1]}")
        for testcase, err in res.errs:
            print(f"Error raised in {testcase.__class__.__name__}: {err[0].__name__}: {err[1]}") #type: ignore
        # # To debug error messages
        if VERBOSE:
            for testcase, err in res.errors:
                print(testcase, err)
    sys.exit(1)